# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: postgres:12.19
    image: postgres:12.19
    restart: always
    ports:
      - 5433:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    container_name: adminer:4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8090:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25